name: Build and publish LoanPay SDK

on:  
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1      
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
    - name: Run SDK build
      run: .\spt\build.ps1
    - name: publish SDK
      run: dotnet nuget push .\build\package\Mwi.LoanPay.*.nupkg --skip-duplicate
