name: Build and publish LoanPay SDK

on:  
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2    
    - name: Run SDK build
      run: .\spt\build.ps1
    - name: publish SDK
      env: 
        NUGET_AUTH_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push .\build\package\Mwi.LoanPay.*.nupkg --api-key ${NUGET_AUTH_KEY}  --source https://api.nuget.org/v3/index.json --skip-duplicate
